/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConversationsConversationIdRouteImport } from './routes/conversations.$conversationId'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as StoriesNewRouteImport } from './routes/stories.new'
import { Route as StoriesStoryIdEditRouteImport } from './routes/stories.$storyId_.edit'
import { Route as StoriesStoryIdConversationsNewRouteImport } from './routes/stories.$storyId_.conversations.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsConversationIdRoute =
  ConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesNewRoute = StoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdEditRoute = StoriesStoryIdEditRouteImport.update({
  id: '/stories/$storyId_/edit',
  path: '/stories/$storyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdConversationsNewRoute =
  StoriesStoryIdConversationsNewRouteImport.update({
    id: '/stories/$storyId_/conversations/new',
    path: '/stories/$storyId/conversations/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/conversations/new': typeof StoriesStoryIdConversationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/conversations/new': typeof StoriesStoryIdConversationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/stories/$storyId_/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId_/conversations/new': typeof StoriesStoryIdConversationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/conversations/$conversationId'
    | '/stories/$storyId'
    | '/stories/new'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/conversations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/conversations/$conversationId'
    | '/stories/$storyId'
    | '/stories/new'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/conversations/new'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/conversations/$conversationId'
    | '/stories/$storyId'
    | '/stories/new'
    | '/stories/$storyId_/edit'
    | '/stories/$storyId_/conversations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ConversationsConversationIdRoute: typeof ConversationsConversationIdRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesNewRoute: typeof StoriesNewRoute
  StoriesStoryIdEditRoute: typeof StoriesStoryIdEditRoute
  StoriesStoryIdConversationsNewRoute: typeof StoriesStoryIdConversationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$conversationId': {
      id: '/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof ConversationsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/new': {
      id: '/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof StoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId_/edit': {
      id: '/stories/$storyId_/edit'
      path: '/stories/$storyId/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof StoriesStoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId_/conversations/new': {
      id: '/stories/$storyId_/conversations/new'
      path: '/stories/$storyId/conversations/new'
      fullPath: '/stories/$storyId/conversations/new'
      preLoaderRoute: typeof StoriesStoryIdConversationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ConversationsConversationIdRoute: ConversationsConversationIdRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesNewRoute: StoriesNewRoute,
  StoriesStoryIdEditRoute: StoriesStoryIdEditRoute,
  StoriesStoryIdConversationsNewRoute: StoriesStoryIdConversationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
